config:
    email_reviewer:
        port: 0
        apiKey: 799cccc7-49e4-420a-b0a8-e4de949ae673
        id: 45fb3f84-c0d7-41fb-bae3-363ca8f8092a
        envVars:
          AZURE_OPENAI_API_KEY: "[YOUR AZURE OPEN API KEY]"
          AZURE_OPENAI_ENDPOINT: "https://[YOUR ENDPOINT].openai.azure.com"
    mailcomposer:
        port: 0
        apiKey: a9ee3d6a-6950-4252-b2f0-ad70ce57d603
        id: 76363e34-d684-4cab-b2b7-2721c772e42f
        envVars:
          AZURE_OPENAI_API_KEY: "[YOUR AZURE OPEN API KEY]"
          AZURE_OPENAI_ENDPOINT: "https://[YOUR ENDPOINT].openai.azure.com"
    org.agntcy.marketing-campaign:
        port: 65222
        apiKey: 12737451-d333-41c2-b3dd-12f15fa59b38
        id: d6306461-ea6c-432f-b6a6-c4feaa81c19b
        envVars:
          AZURE_OPENAI_API_KEY: "[YOUR AZURE OPEN API KEY]"
          AZURE_OPENAI_ENDPOINT: "https://[YOUR ENDPOINT].openai.azure.com"
          SENDGRID_HOST: "http://host.docker.internal:8080"
          SENDGRID_API_KEY: "[YOUR SENDGRID_API_KEY:]"
