# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "network-of-assistants.file-assistant.fullname" . }}
  labels:
    {{- include "network-of-assistants.file-assistant.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "network-of-assistants.file-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "network-of-assistants.file-assistant.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "network-of-assistants.file-assistant.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
      {{- with .Values.networkOfAssistants.fileAssistant.podSecurityContext }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.networkOfAssistants.fileAssistant.image.repository }}:{{ .Values.networkOfAssistants.fileAssistant.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.networkOfAssistants.fileAssistant.image.pullPolicy }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SLIM_ENDPOINT
              value: "http://{{ include "network-of-assistants.slim.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.networkOfAssistants.slim.service.port }}"
            - name: ASSISTANT_DOC_DIR
              value: "{{ .Values.networkOfAssistants.fileAssistant.volume.mountPath }}"
            - name: WITH_OBS
              value: "{{ .Values.observability.enabled }}"
            - name: OTLP_HTTP_ENDPOINT
              value: "{{ .Values.observability.opentelemetry.http.endpoint }}"
            - name: OTLP_GRPC_ENDPOINT
              value: "{{ .Values.observability.opentelemetry.grpc.endpoint }}"
            - name: ASSISTANT_LLM_TYPE
              value: "{{ .Values.networkOfAssistants.fileAssistant.llm.type }}"
            - name: ASSISTANT_LLM_MODEL
              value: "{{ .Values.networkOfAssistants.fileAssistant.llm.model }}"
            - name: FILE_URL
              value: "{{ .Values.networkOfAssistants.fileAssistant.fileURL }}"
            {{ $llmSecretName := include "network-of-assistants.file-assistant.llmRemoteAPISecretName" . }}
            {{- if .Values.networkOfAssistants.fileAssistant.llm.remoteAPISecret.existingSecret }}
            {{ $llmSecretName = .Values.networkOfAssistants.fileAssistant.llm.remoteAPISecret.existingSecret }}
            {{- end }}
            - name: ASSISTANT_LLM_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $llmSecretName }}
                  key: {{ .Values.networkOfAssistants.fileAssistant.llm.remoteAPISecret.secretKeys.address }}
            - name: ASSISTANT_LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $llmSecretName }}
                  key: {{ .Values.networkOfAssistants.fileAssistant.llm.remoteAPISecret.secretKeys.key }}
            - name: ASSISTANT_RAG_TYPE
              value: "{{ .Values.networkOfAssistants.fileAssistant.rag.type }}"
            - name: ASSISTANT_RAG_MODEL
              value: "{{ .Values.networkOfAssistants.fileAssistant.rag.model }}"
            {{ $ragSecretName := include "network-of-assistants.file-assistant.ragRemoteAPISecretName" . }}
            {{- if .Values.networkOfAssistants.fileAssistant.rag.remoteAPISecret.existingSecret }}
            {{ $ragSecretName = .Values.networkOfAssistants.fileAssistant.rag.remoteAPISecret.existingSecret }}
            {{- end }}
            - name: ASSISTANT_RAG_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $ragSecretName }}
                  key: {{ .Values.networkOfAssistants.fileAssistant.rag.remoteAPISecret.secretKeys.address }}
            - name: ASSISTANT_RAG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $ragSecretName }}
                  key: {{ .Values.networkOfAssistants.fileAssistant.rag.remoteAPISecret.secretKeys.key }}
          {{- if .Values.networkOfAssistants.fileAssistant.environment }}
          {{- range $key, $val := .Values.networkOfAssistants.fileAssistant.environment }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          {{- end }}
          {{- if .Values.networkOfAssistants.environment }}
          {{- range $key, $val := .Values.networkOfAssistants.environment }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: file-assistant-volume
              mountPath: {{ .Values.networkOfAssistants.fileAssistant.volume.mountPath }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: file-assistant-volume
          persistentVolumeClaim:
            claimName: {{ include "network-of-assistants.file-assistant.fullname" . }}-pvc
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
