# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "network-of-assistants.slim.fullname" . }}-config
  labels:
    {{- include "network-of-assistants.slim.labels" . | nindent 4 }}
data:
  server-config.yaml: |
    # Copyright AGNTCY Contributors (https://github.com/agntcy)
    # SPDX-License-Identifier: Apache-2.0

    tracing:
      log_level: info
      display_thread_names: true
      display_thread_ids: true
    
    runtime:
      n_cores: 0
      thread_name: "data-plane-gateway"
      drain_timeout: 10s

    services:
      slim/0:
        pubsub:
          servers:
            - endpoint: "0.0.0.0:{{ .Values.networkOfAssistants.slim.service.port }}"
              tls:
                insecure: true

          clients: []