# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "network-of-assistants.user-proxy.fullname" . }}
  labels:
    {{- include "network-of-assistants.user-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networkOfAssistants.userProxy.service.type }}
  ports:
    - port: {{ .Values.networkOfAssistants.userProxy.service.port }}
      targetPort: {{ .Values.networkOfAssistants.userProxy.service.port }}
      protocol: TCP
  selector:
    {{- include "network-of-assistants.user-proxy.selectorLabels" . | nindent 4 }}
