replicaCount: 1

image:
  repository: "ghcr.io/agntcy/slim/control-plane"
  pullPolicy: IfNotPresent
  tag: "1.0.0-dev.07"

config:
  northbound:
    httpHost: 0.0.0.0
    httpPort: "{{ .Values.service.north.port }}"

  southbound:
    httpHost: 0.0.0.0
    httpPort: "{{ .Values.service.south.port }}"

  database:
    filePath: ""

  logging:
    level: DEBUG
  reconciler:
    maxRequeues: 15
    maxNumOfReconciles: 1000

spire:
  enabled: false
  # Slim Controller SVIDs will be federated with these trust domains
  trustedDomains: []
    # - cluster-a.example.org
    # - cluster-b.example.org

env:
  - name: NB_API_HTTP_HOST
    value: "0.0.0.0"
  - name: SB_API_HTTP_HOST
    value: "0.0.0.0"

service:
  type: ClusterIP
  south:
    port: 50052
  north:
    port: 50051

ingress:
  enabled: true
  className: "nginx-internal"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippet: |
      grpc_socket_keepalive on;
      client_header_timeout 60m;
      client_body_timeout 60m;
  hosts:
    - host: control-plane-public-address
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: slim-control-plane-tls
      hosts:
        - control-plane-public-address

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
