[project]
name = "agp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "agp-bindings==0.2.1",
]

<<<<<<< HEAD

=======
>>>>>>> ca3fa6a (feat(user_proxy): init user_proxy)
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.build]
<<<<<<< HEAD
includes = ["agp/"]
=======
includes = ["agp/"]
>>>>>>> ca3fa6a (feat(user_proxy): init user_proxy)
