[project]
name = "agp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agp-bindings==0.2.0"
]

[tool.uv.workspace]
members = ["pdf_assistant"]

[dependency-groups]
dev = [
    "ruff<1.0.0,>=0.9.3",
]
