# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- if not .Values.networkOfAssistants.moderator.llm.remoteAPISecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "network-of-assistants.moderator.llmRemoteAPISecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "network-of-assistants.moderator.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.networkOfAssistants.moderator.llm.remoteAPISecret.secretKeys.address }}: {{ required "LLM endpoint is required!" .Values.networkOfAssistants.moderator.llm.remoteAPISecret.address | b64enc }}
  {{ .Values.networkOfAssistants.moderator.llm.remoteAPISecret.secretKeys.key }}: {{ required "LLM API key is required!" .Values.networkOfAssistants.moderator.llm.remoteAPISecret.key | b64enc }}
---
{{- end }}
