# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

services:

  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    networks:
      - app_network
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - app_network
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      clickhouse-server:
        condition: service_healthy

  noa-slim:
    image: ghcr.io/agntcy/slim:0.3.15
    networks:
      - app_network
    ports:
    - "46357:46357"
    volumes:
      - ./noa-slim/slim-config.yaml:/config.yaml
    command: ["/slim", "--config", "/config.yaml"]

  noa-moderator:
    build:
      context: .
      dockerfile: noa-moderator/Dockerfile
    networks:
      - app_network
    depends_on:
      - noa-slim
      - otel-collector
    volumes:
      - ./dir:/app/dir
    environment:
      - MODERATOR_LLM_TYPE=openai
      - MODERATOR_LLM_MODEL=gpt-4o
      - MODERATOR_LLM_BASE_URL
      - MODERATOR_LLM_API_KEY
      - SLIM_ENDPOINT=http://noa-slim:46357
      - AGENTS_DIR=/app/dir/datamodels
      - WITH_OBS=true
      - OTLP_HTTP_ENDPOINT=http://otel-collector:4318
      - OTLP_GRPC_ENDPOINT=http://otel-collector:4317

  noa-file-assistant:
    build:
      context: .
      dockerfile: noa-file-assistant/Dockerfile
    networks:
      - app_network
    depends_on:
      - noa-slim
      - noa-moderator
      - otel-collector
    volumes:
      - ./noa-file-assistant/files:/home/files
    environment:
      - ASSISTANT_LLM_TYPE=openai
      - ASSISTANT_LLM_MODEL=gpt-4o
      - ASSISTANT_LLM_BASE_URL
      - ASSISTANT_LLM_API_KEY
      - ASSISTANT_RAG_BASE_URL
      - ASSISTANT_RAG_API_KEY
      - SLIM_ENDPOINT=http://noa-slim:46357
      - ASSISTANT_ID=noa-file-assistant
      - ASSISTANT_DOC_DIR=/home/files
      - FILE_URL=https://arxiv.org/pdf/2410.10934?
      - WITH_OBS=true
      - OTLP_HTTP_ENDPOINT=http://otel-collector:4318
      - OTLP_GRPC_ENDPOINT=http://otel-collector:4317

  noa-web-surfer:
    build:
      context: .
      dockerfile: noa-web-surfer/Dockerfile
    networks:
      - app_network
    depends_on:
      - noa-slim
      - noa-moderator
      - otel-collector
    environment:
      - WEB_SURFER_LLM_TYPE=openai
      - WEB_SURFER_LLM_MODEL=gpt-4o
      - WEB_SURFER_LLM_BASE_URL
      - WEB_SURFER_LLM_API_KEY
      - SLIM_ENDPOINT=http://noa-slim:46357
      - WEB_SURFER_ID=noa-web-surfer-assistant
      - WITH_OBS=true
      - OTLP_HTTP_ENDPOINT=http://otel-collector:4318
      - OTLP_GRPC_ENDPOINT=http://otel-collector:4317

  noa-math-assistant:
    build:
      context: .
      dockerfile: noa-math-assistant/Dockerfile
    networks:
      - app_network
    depends_on:
      - noa-slim
      - noa-moderator
      - otel-collector
    environment:
      - MATH_ASSISTANT_LLM_TYPE=openai
      - MATH_ASSISTANT_LLM_MODEL=gpt-4o
      - MATH_ASSISTANT_LLM_BASE_URL
      - MATH_ASSISTANT_LLM_API_KEY
      - SLIM_ENDPOINT=http://noa-slim:46357
      - MATH_ASSISTANT_ID=noa-math-assistant
      - WITH_OBS=true
      - OTLP_HTTP_ENDPOINT=http://otel-collector:4318
      - OTLP_GRPC_ENDPOINT=http://otel-collector:4317

  noa-user-proxy:
    build:
      context: .
      dockerfile: noa-user-proxy/Dockerfile
    networks:
      - app_network
    ports:
      - "8000:8000"
    environment:
      - SLIM_ENDPOINT=http://noa-slim:46357
    stdin_open: true
    tty: true
    depends_on:
      - noa-slim
      - noa-moderator
      - noa-file-assistant
      - noa-web-surfer
      - noa-math-assistant
      - otel-collector

networks:
  app_network:
    driver: bridge
