---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github:
        patterns:
          - "actions/*"
          - "github/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10

