version: '3.8'

services:
  moderator:
    build:
      context: .
      dockerfile: moderator/Dockerfile
    networks:
      - app_network
    environment:
      - AZURE_OPENAI_ENDPOINT=https://jarvis-dev-east-us-2.openai.azure.com
      - AZURE_OPENAI_API_KEY=d7e6fe7336624051ab4c47d12ee05b47
      - AZURE_OPENAI_DEPLOYMENT_NAME=gpt-4o-mini
      - AZURE_OPENAI_API_VERSION=2024-08-01-preview
      - AGP_ENDPOINT=http://agp:46357
      - MODERATOR_AGENTS_DIR=/ads/datamodels

  user_proxy:
    build:
      context: .
      dockerfile: user_proxy/Dockerfile
    networks:
      - app_network
    environment:
      - AGP_ENDPOINT=http://agp:46357
    stdin_open: true
    tty: true

  pdf_assistant:
    build:
      context: .
      dockerfile: pdf_assistant/Dockerfile
    networks:
      - app_network
    environment:
      - ASSISTANT_LLM_ENDPOINT=https://jarvis-dev-east-us-2.openai.azure.com
      - ASSISTANT_LLM_KEY=d7e6fe7336624051ab4c47d12ee05b47
      - ASSISTANT_LLM_TYPE=azure
      - ASSISTANT_ASSISTANT_ID=nexus-assistant
      - ASSISTANT_DOC_DIR=/nexus
      - AGP_ENDPOINT=http://agp:46357

  agp:
    image: ghcr.io/agntcy/agp/gw:0.3.11
    networks:
      - app_network
    volumes:
      - ./agp-config.yaml:/config.yaml
    command: ["/gateway", "--config", "/config.yaml"]

networks:
  app_network:
    driver: bridge
